# Generated by Django 6.0.3 on 2026-03-05 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='genres',
            new_name='Genre',
        ),
    ]
