# Generated by Django 6.0.3 on 2026-03-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_genres_genre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='genres',
        ),
    ]
