# Generated by Django 6.0.3 on 2026-03-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_genre_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='name_ru',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
